# 
# PURPOSE:
#
#   1. keep *github actions* files up to date
#   2. keep *docker* related files up to date
#
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "develop"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "develop"
